services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /etc/komodo/stacks/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.seanzhong.com
      HOMEPAGE_VAR_PROXMOX_PASSWORD: $PROXMOX_API_TOKEN
      HOMEPAGE_VAR_PIHOLE_PASSWORD: $PIHOLE_PASSWORD
      HOMEPAGE_VAR_NPM_PASSWORD: $NPM_PASSWORD
      HOMEPAGE_VAR_UNIFI_KEY: $UNIFI_KEY
      HOMEPAGE_VAR_TRUENAS_KEY: $TRUENAS_KEY
      HOMEPAGE_VAR_HOMEASSISTANT_KEY: $HOMEASSISTANT_KEY
      HOMEPAGE_VAR_JELLYFIN_KEY: $JELLYFIN_KEY
      HOMEPAGE_VAR_PORTAINER_KEY: $PORTAINER_KEY
      HOMEPAGE_VAR_TRAEFIK_PASSWORD: $TRAEFIK_PASSWORD
      HOMEPAGE_VAR_GRAFANA_PASSWORD: $GRAFANA_PASSWORD
      HOMEPAGE_VAR_K8S_PORTAINER_KEY: $K8S_PORTAINER_KEY
      HOMEPAGE_VAR_NEXTCLOUD_KEY: $NEXTCLOUD_KEY
    restart: unless-stopped
