# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- VM/Container Managenment:
    - Proxmox:
        href: https://proxmox.seanzhong.com/
        icon: https://git.proxmox.com/?p=pve-manager.git;a=blob;f=www/images/favicon.ico;h=ba0c9af606c2766dfd56afa3a49f7e09a700f8fc;hb=refs/heads/master
        description: Proxmox Web Ui
    - Portainer:
        href: https://docker.seanzhong.com/
        icon: https://cloud.seanzhong.com/index.php/s/cfepD5DiTkbPjde/download/Portainer.svg
        description: Portainer Web Ui

- Networking:
    - Pi-hole:
        href: http://pi.hole/
        icon: https://cloud.seanzhong.com/index.php/s/DSLxi7dS75pdwtB/download/pihole.svg
        description: Pi-hole Web Ui
    - Router:
        href: http://router.seanzhong.com/
        icon: https://cloud.seanzhong.com/index.php/s/AFPEALoNNsT44N9/download/router.png
        description: DDWRT interface
    - Nginx Proxy Manager:
        href: http://npm.seanzhong.com:81/
        icon: https://cloud.seanzhong.com/index.php/s/DbxT3XzcMtxjsDC/download/icon.png
        description: Nginx Proxy Manager admin dashboard

- Media:
    - Jellyfin:
        href: http://jellyfin.seanzhong.com/
        icon: https://cloud.seanzhong.com/index.php/s/S5xcAWS3yWLcN6L/download/jellyfin.svg
        description: Jellyfin media player
    - TrueNas:
        href: https://truenas.seanzhong.com/
        icon: https://cloud.seanzhong.com/index.php/s/JzyBYZXynW7ppYG/download/truenas-scale.svg
        description: TrueNas Web Ui
    - NextCloud:
        href: https://cloud.seanzhong.com/
        icon: https://cloud.seanzhong.com/index.php/s/Tg3xBLcYbxqbFm2/download/nextcloud.512x512.png
        descrition: NextCloud Web Ui

- Home:
    - Home Assistant:
        href: https://ha.seanzhong.com/
        icon: https://cloud.seanzhong.com/index.php/s/AMJQTzfr2tqQCaw/download/file-type-homeassistant.svg
        description: Homeassistant Web Ui
