# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Managenment:
    - Proxmox:
        href: https://proxmox.seanzhong.com/
        description: Proxmox Web Ui
    - Portainer:
        href: https://docker.seanzhong.com/
        description: Portainer Web Ui

- Media:
    - Jellyfin:
        href: http://jellyfin.seanzhong.com
        description: Jellyfin media player

- Home:
    - Home Assistant:
        href: https://ha.seanzhong.com/
        description: Homeassistant Web Ui
