# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Managenment:
    - Proxmox:
        href: https://proxmox.seanzhong.com
        description: Proxmox Web Ui

- Media:
    - Jellyfin:
        href: http://192.168.10.172:8096/
        description: Jellyfin media player

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is  ^=^x^n
