# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Managenment:
    - Proxmox:
        href: https://proxmox.seanzhong.com/
        icon: https://git.proxmox.com/?p=pve-manager.git;a=blob;f=www/images/favicon.ico;h=ba0c9af606c2766dfd56afa3a49f7e09a700f8fc;hb=refs/heads/master
        description: Proxmox Web Ui
    - Portainer:
        href: https://docker.seanzhong.com/
        description: Portainer Web Ui

- Media:
    - Jellyfin:
        href: http://jellyfin.seanzhong.com
        description: Jellyfin media player

- Home:
    - Home Assistant:
        href: https://ha.seanzhong.com/
        description: Homeassistant Web Ui
