# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Managenment:
    - Proxmox:
        href: https://proxmox.seanzhong.com/
        icon: https://git.proxmox.com/?p=pve-manager.git;a=blob;f=www/images/favicon.ico;h=ba0c9af606c2766dfd56afa3a49f7e09a700f8fc;hb=refs/heads/master
        description: Proxmox Web Ui
    - Portainer:
        href: https://docker.seanzhong.com/
        description: Portainer Web Ui
    - Pi-hole:
        href: http://pi.hole/
        description: Pi-hole Web Ui

- Media:
    - Jellyfin:
        href: http://jellyfin.seanzhong.com/
        icon: https://raw.githubusercontent.com/jellyfin/jellyfin-web/refs/heads/master/src/favicon.ico
        description: Jellyfin media player
    - TrueNas:
        href: https://truenas.seanzhong.com/
        description: TrueNas Web Ui

- Home:
    - Home Assistant:
        href: https://ha.seanzhong.com/
        icon: https://cloud.seanzhong.com/remote.php/dav/files/sean/HomepageIcons/file-type-homeassistant.svg
        description: Homeassistant Web Ui
