  GNU nano 7.2                                                                                              services.yaml                                                                                                       
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media:
    - Jellyfin:
        href: http://192.168.10.172:8096/
        description: Jellyfin media player
- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is  ^=^x^n
