# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- VM/Container Managenment:
    - Proxmox:
        href: https://proxmox.seanzhong.com/
        icon: https://git.proxmox.com/?p=pve-manager.git;a=blob;f=www/images/favicon.ico;h=ba0c9af606c2766dfd56afa3a49f7e09a700f8fc;hb=refs/heads/master
        description: Proxmox Web Ui
        widget:
          type: proxmox
          url: https://proxmox.seanzhong.com
          username: api@pam!homepage
          password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}

    - Portainer:
        href: https://docker.seanzhong.com/
        icon: https://cloud.seanzhong.com/index.php/s/cfepD5DiTkbPjde/download/Portainer.svg
        description: Docker Portainer Web Ui
        widget:
          type: portainer
          url: https://docker.seanzhong.com
          env: 2
          key: {{HOMEPAGE_VAR_PORTAINER_KEY}}

    - K8s:
        href: https://k8s.seanzhong.com/
        icon: https://cloud.seanzhong.com/index.php/s/cfepD5DiTkbPjde/download/Portainer.svg
        description: Kubernetes Portainer Web Ui
    - Grafana:
        href: http://grafana.seanzhong.com/
        icon: https://cloud.seanzhong.com/index.php/s/JsCqbfjXi6xrGbX/download/grafana_icon_130916.png
        description: Grafana Monitoring
        widget:
          type: grafana
          version: 2
          alerts: alertmanager
          url: https://grafana.seanzhong.com
          username: admin
          password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}

- Networking:
    - Pi-hole:
        href: http://pihole.seanzhong.com/admin
        icon: https://cloud.seanzhong.com/index.php/s/DSLxi7dS75pdwtB/download/pihole.svg
        description: Pi-hole Web Ui
        widget:
          type: pihole
          url: http://pihole.seanzhong.com
          version: 6
          key: {{HOMEPAGE_VAR_PIHOLE_PASSWORD}}

    - Router:
        href: https://router.seanzhong.com/
        icon: https://cloud.seanzhong.com/index.php/s/AFPEALoNNsT44N9/download/router.png
        description: Unifi interface
        widget:
          type: unifi
          url: https://router.seanzhong.com
          key: {{HOMEPAGE_VAR_UNIFI_KEY}}

    - Nginx Proxy Manager:
        href: http://npm.seanzhong.com:81/
        icon: https://cloud.seanzhong.com/index.php/s/DbxT3XzcMtxjsDC/download/icon.png
        description: Nginx Proxy Manager admin dashboard
        widget:
          type: npm
          url: http://npm.seanzhong.com:81
          username: szhrune@gmail.com
          password: {{HOMEPAGE_VAR_NPM_PASSWORD}}

    - Traefik:
        href: http://traefik.seanzhong.com
        icon: https://cloud.seanzhong.com/index.php/s/g8Hy25JXbg6RyHt/download/images.png
        description: Traefik dashboard
        username: sean
        password: {{HOMEPAGE_VAR_TRAEFIK_PASSWORD}}

- Media:
    - Jellyfin:
        href: http://jellyfin.seanzhong.com/
        icon: https://cloud.seanzhong.com/index.php/s/S5xcAWS3yWLcN6L/download/jellyfin.svg
        description: Jellyfin media player
        widget:
          type: jellyfin
          url: http://jellyfin.seanzhong.com
          key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          enableMediaControl: false # optional, defaults to true
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true
    - TrueNas:
        href: https://truenas.seanzhong.com/
        icon: https://cloud.seanzhong.com/index.php/s/JzyBYZXynW7ppYG/download/truenas-scale.svg
        description: TrueNas Web Ui
        widget:
          type: truenas
          url: https://truenas.seanzhong.com
          key: {{HOMEPAGE_VAR_TRUENAS_KEY}}
          enablePools: true

    - NextCloud:
        href: https://cloud.seanzhong.com/
        icon: https://cloud.seanzhong.com/index.php/s/Tg3xBLcYbxqbFm2/download/nextcloud.512x512.png
        descrition: NextCloud Web Ui

- Home:
    - Home Assistant:
        href: https://ha.seanzhong.com/
        icon: https://cloud.seanzhong.com/index.php/s/AMJQTzfr2tqQCaw/download/file-type-homeassistant.svg
        description: Homeassistant Web Ui
        widget:
          type: homeassistant
          url: https://ha.seanzhong.com
          key: {{HOMEPAGE_VAR_HOMEASSISTANT_KEY}}
          custom:
            - state: sensor.hallway_motion_sensor_temperature
              label: Hallway Temperature Sensor
