---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- openmeteo:
    label: Stockholm # optional
    latitude: 59.353193
    longitude: 18.085817
    timezone: Europe/Stockholm # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1

- search:
    provider: google
    target: _blank
